services:
  # Nodo 1: Laravel
  nodo-laravel:
    build:
      context: ./nodo-laravel
    container_name: blockchain-laravel
    ports:
      - "8010:8000"
    volumes:
      - ./nodo-laravel:/var/www/html
    networks:
      - blockchain-net
    environment:
      - PEER_NODES=http://blockchain-express:3000,http://blockchain-next:3000

  # Nodo 2: Express
  nodo-express:
    build:
      context: ./nodo-express
    container_name: blockchain-express
    ports:
      - "8011:3000"
    volumes:
      - ./nodo-express:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - blockchain-net
    environment:
      - PEER_NODES=http://blockchain-laravel:8000,http://blockchain-next:3000

  # Nodo 3: Next.js
  nodo-nextjs:
    build:
      context: ./nodo-nextjs
    container_name: blockchain-next
    ports:
      - "8012:3000"
    volumes:
      - ./nodo-nextjs:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
    networks:
      - blockchain-net
    environment:
      - PEER_NODES=http://blockchain-laravel:8000,http://blockchain-express:3000

networks:
  blockchain-net:
    driver: bridge